name: Sync to Hugging Face Space

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "vinayakikshatriya@gmail.com"
          git config --global user.name "vinayaknaik4857"

          git clone https://vinayaknaik4857:$HF_TOKEN@huggingface.co/spaces/vinayaknaik4857/openenv-email-triage hf_repo
          
          rsync -av --exclude '.git' ./ hf_repo/

          cd hf_repo
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push
